format = """
[░▒▓](#769ff0)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[ ](fg:#394260 bg:#21273600)\
"""

add_newline = false

[directory]
style = "fg:#090c0c bg:#769ff0"
format = "[ $path ]($style)"

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'


[line_break]
disabled = true

[package]
disabled = true

[nodejs]
disabled = true

[rust]
disabled = true

[lua]
disabled = true

[c]
disabled = true

[cmd_duration]
disabled = true

[aws]
disabled = true

[docker_context]
disabled = true
