#!/usr/bin/env bash

[ $# -eq 1 ] || called_with_arg=1

if [[ -z $called_with_arg ]]; then
    selected=$1
else
    selected=$(find  ~/ ~/.dotfiles ~/.dotfiles/.config ~/Documents ~/Documents/work ~/Documents/personal ~/Documents/writing/published ~/Documents/writing/unpublished -maxdepth 1 -mindepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected 
fi

if [[ $(tmux list-windows -t $selected_name | wc -l) -eq 1 ]] && [[ -z $called_with_arg ]]; then
    tmux neww -t $selected_name -c $selected
fi

tmux switch-client -t $selected_name:1
